#--SpringBoot Configuration--
spring.application.name=ChatServer
spring.main.banner-mode=off
logging.pattern.console=%d{HH:mm:ss} - %msg%n
logging.level.root=WARN
server.address=0.0.0.0
# File Uploading Config
spring.web.resources.static-locations=classpath:/static/,file:///${user.dir}/uploads/
server.servlet.mime-mappings.jpg=image/jpeg
server.servlet.mime-mappings.png=image/png
server.servlet.mime-mappings.gif=image/gif
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
#--SqLite DB Configuration--
spring.datasource.url=jdbc:sqlite:data/chat.db?foreign_keys=on
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=never
spring.datasource.username=
spring.datasource.password=
#--Hibernate Configuration--
spring.jpa.properties.hibernate.foreign_keys=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
hbm2ddl.auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false