#--SpringBoot Configuration--
spring.application.name=ChatServer
spring.main.banner-mode=off
logging.pattern.console=%d{HH:mm:ss} - %msg%n
#--SqLite DB Configuration--
spring.datasource.url=jdbc:sqlite:data/chat.db?foreign_keys=on
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=never
spring.datasource.username=
spring.datasource.password=
#--Hibernate Configuration--
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
