package com.yago.chatServer.model;

public enum WebSocketAction {
    ADD_CONTACT,
    DELETE_CONTACT,
    MESSAGE_RECEIVED,
    MESSAGE_READ,
    MESSAGE_DELETED,
    USER_CONNECTED,
    USER_DISCONNECTED,
    USER_DISCONNECTED_FROM_GROUP_CHAT,
    USER_LEFT_GROUP_CHAT,
    USER_JOINED_GROUP_CHAT,
    GET_CONTACTS_ONLINE_STATUS,
    ERROR;
}
